export const targetAudience = [
  { name: "Pr. Oumtanaga Souleymane", affiliation: "INPHB, Côte d’Ivoire", photo: "/img/oumtanaga.jpg" },
  { name: "Dr (MC) Diaby Moustapha", affiliation: "ESATIC, Côte d’Ivoire", photo: "/img/pdiaby.jpg" },
  { name: "Dr. Diarra Mamadou", affiliation: "UFHB, Côte d’Ivoire", photo: "/img/diarra.jpg" },
  { name: "Dr. Kamagaté Beman", affiliation: "ESATIC, Côte d’Ivoire", photo: "/img/kamagate.jpg" },
  { name: "Dr. Kouakou Konan", affiliation: "UVCI, Côte d’Ivoire", photo: "/img/kouakou.jpg" },
  { name: "Pr. Kouadio N’Guessan", affiliation: "Université Nangui Abrogoua, Côte d’Ivoire", photo: "/img/kouadio.jpg" },
  { name: "Dr. Konaté Moussa", affiliation: "Université de San Pedro, Côte d’Ivoire", photo: "/img/konate.jpg" },
  { name: "Pr. Abdoulaye Cissé", affiliation: "Université Nazi Boni, Burkina Faso", photo: "/img/cisse.jpg" },
  { name: "Dr. Kaboré Lassina", affiliation: "Université Joseph Ki-Zerbo, Burkina Faso", photo: "/img/kabore.jpg" },
  { name: "Dr. Seydou Traoré", affiliation: "USTTB, Mali", photo: "/img/traore.jpg" },
  { name: "Pr. Alioune Ngom", affiliation: "Université Gaston Berger, Sénégal", photo: "/img/ngom.jpg" },
  { name: "Dr. Aminata Fall", affiliation: "UCAD, Sénégal", photo: "/img/fall.jpg" },
  { name: "Dr. Fatoumata Diallo", affiliation: "Université de Conakry, Guinée", photo: "/img/diallo.jpg" },
  { name: "Pr. Hamadou Saliah-Hassane", affiliation: "UQAM, Niger/Canada", photo: "/img/saliah.jpg" },
];
